export const PlatformOptions = [
    { name: "Playstation 1", value: "PLAYSTATION1" },
    { name: "Playstation 2", value: "PLAYSTATION2" },
    { name: "Playstation 3", value: "PLAYSTATION3" },
    { name: "Playstation 4", value: "PLAYSTATION4" },
    { name: "Playstation 5", value: "PLAYSTATION5" },
    { name: "Xbox classic", value: "XBOXCLASSIC" },
    { name: "Xbox 360", value: "XBOX360" },
    { name: "Xbox One", value: "XBOXONE" },
    { name: "NES", value: "NES" },
    { name: "Super Nintendo", value: "SNES" },
    { name: "Gameboy", value: "GAMEBOYCLASSIC" },
    { name: "Gameboy Advance", value: "GAMEBOYADVANCE" },
    { name: "Nintendo 64", value: "NINTENDO64" },
    { name: "Gamecube", value: "GAMECUBE" },
    { name: "Wii", value: "WII" },
    { name: "Wii U", value: "WIIU" },
    { name: "Switch", value: "SWITCH" },
    { name: "PC", value: "PC" },
    { name: "Overig", value: "OTHER" },
];